name: Build and Push

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'
          cache: npm

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12.1'

      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: 'jre'

      - name: Install Dependencies and Build
        run: npm ci

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Checkout to develop-builds
        uses: actions/checkout@v3
        with:
          ref: develop-builds

      - name: Clear out things
        run: |
          rm -rf ./*

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: './'

      - name: Clear artifact
        run: |
          rm -f artifact.tar

      - name: Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: ${{ github.event.head_commit.message }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
