name: Build and Push

on:
  push:
    branches:
      - develop-builds

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12.1'

      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: 'jre'

      - name: Install Dependencies and Build
        run: npm ci

      - name: Commit and Push Build
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Update Builds"
          git push origin develop-builds