name: Update develop-builds

on:
  workflow_dispatch:
    inputs: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop-builds branch
        uses: actions/checkout@v4
        with:
          ref: develop-builds
          fetch-depth: 0

      - name: Set up GitHub user
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Merge develop into develop-builds
        run: |
          git fetch origin develop:develop
          git merge --no-ff --no-edit develop || {
            echo "Merge conflict detected. Please resolve manually.";
            exit 1;
          }

      - name: Push changes
        if: success()
        run: |
          git push origin develop-builds
